package io.velocityapi;

import io.velocityapi.annotations.Body;
import io.velocityapi.annotations.Description;
import io.velocityapi.annotations.Param;
import io.velocityapi.annotations.Query;

import java.lang.reflect.Method;
import java.lang.reflect.Parameter;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.RecordComponent;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * OpenAPI generator for VelocityAPI routes.
 * Produces a JSON string (OpenAPI 3.0).
 */
public final class OpenAPIGenerator {
    private final List<RouteDefinition> routes;
    private final Map<Class<?>, String> schemaRegistry;

    private final Map<String, Map<String, Object>> componentsSchemas = new HashMap<>();

    public OpenAPIGenerator(List<RouteDefinition> routes, Map<Class<?>, String> schemaRegistry) {
        this.routes = routes;
        this.schemaRegistry = schemaRegistry;
    }

    public String generate() {
        Map<String, Object> spec = new HashMap<>();
        spec.put("openapi", "3.0.0");

        Map<String, Object> info = new HashMap<>();
        info.put("title", "VelocityAPI");
        info.put("version", "1.0.0");
        info.put("description", "Auto-generated by VelocityAPI");
        spec.put("info", info);

        Map<String, Object> paths = new HashMap<>();
        spec.put("paths", paths);

        for (RouteDefinition route : routes) {
            Method m = route.handlerMethod();
            String path = route.path();
            String httpLower = route.httpMethod().toLowerCase();

            Map<String, Object> pathItem =
                (Map<String, Object>) paths.computeIfAbsent(path, k -> new HashMap<>());

            Map<String, Object> operation = new HashMap<>();
            operation.put("summary", m.getName());

            Description descAnn = m.getAnnotation(Description.class);
            operation.put("description", descAnn == null ? "" : descAnn.value());

            List<Map<String, Object>> parameters = new ArrayList<>();
            Map<String, Object> requestBody = null;

            for (Parameter p : m.getParameters()) {
                if (p.isAnnotationPresent(Param.class)) {
                    Param ann = p.getAnnotation(Param.class);
                    Map<String, Object> schema = schemaForType(p.getParameterizedType());
                    Map<String, Object> param = new HashMap<>();
                    param.put("name", ann.value());
                    param.put("in", "path");
                    param.put("required", true);
                    param.put("schema", schema);
                    parameters.add(param);
                } else if (p.isAnnotationPresent(Query.class)) {
                    Query ann = p.getAnnotation(Query.class);
                    Map<String, Object> schema = schemaForType(p.getParameterizedType());
                    Map<String, Object> param = new HashMap<>();
                    param.put("name", ann.value());
                    param.put("in", "query");
                    param.put("required", false);
                    param.put("schema", schema);
                    parameters.add(param);
                } else if (p.isAnnotationPresent(Body.class)) {
                    Map<String, Object> contentSchema = schemaForType(p.getParameterizedType());

                    Map<String, Object> mediaType = new HashMap<>();
                    mediaType.put("schema", contentSchema);

                    Map<String, Object> content = new HashMap<>();
                    content.put("application/json", mediaType);

                    requestBody = new HashMap<>();
                    requestBody.put("required", true);
                    requestBody.put("content", content);
                }
            }

            if (!parameters.isEmpty()) {
                operation.put("parameters", parameters);
            }
            if (requestBody != null) {
                operation.put("requestBody", requestBody);
            }

            Map<String, Object> responses = new HashMap<>();
            Map<String, Object> ok = new HashMap<>();
            ok.put("description", "Success");
            responses.put("200", ok);

            Map<String, Object> unprocessable = new HashMap<>();
            unprocessable.put("description", "Validation error");
            responses.put("422", unprocessable);

            operation.put("responses", responses);

            pathItem.put(httpLower, operation);
        }

        if (!componentsSchemas.isEmpty()) {
            Map<String, Object> components = new HashMap<>();
            components.put("schemas", componentsSchemas);
            spec.put("components", components);
        }

        try {
            return new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(spec);
        } catch (Exception e) {
            throw new RuntimeException("Failed to serialize OpenAPI spec", e);
        }
    }

    private Map<String, Object> schemaForType(Type type) {
        if (type instanceof ParameterizedType pt) {
            Type raw = pt.getRawType();
            if (raw instanceof Class<?> rawClass && List.class.isAssignableFrom(rawClass)) {
                Type arg = pt.getActualTypeArguments()[0];
                Map<String, Object> items = schemaForType(arg);
                Map<String, Object> arr = new HashMap<>();
                arr.put("type", "array");
                arr.put("items", items);
                return arr;
            }

            if (raw instanceof Class<?> rawClass) {
                return schemaForClass(rawClass);
            }
        }

        if (type instanceof Class<?> cls) {
            return schemaForClass(cls);
        }

        return Map.of("type", "string");
    }

    private Map<String, Object> schemaForClass(Class<?> cls) {
        if (cls.equals(int.class) || cls.equals(Integer.class)) return Map.of("type", "integer");
        if (cls.equals(long.class) || cls.equals(Long.class)) return Map.of("type", "integer");
        if (cls.equals(double.class) || cls.equals(Double.class) || cls.equals(float.class) || cls.equals(Float.class)) {
            return Map.of("type", "number");
        }
        if (cls.equals(boolean.class) || cls.equals(Boolean.class)) return Map.of("type", "boolean");
        if (cls.equals(String.class)) return Map.of("type", "string");

        String name = schemaRegistry.computeIfAbsent(cls, c -> c.getSimpleName());
        componentsSchemas.computeIfAbsent(name, n -> buildObjectSchema(cls));

        return Map.of("$ref", "#/components/schemas/" + name);
    }

    private Map<String, Object> buildObjectSchema(Class<?> cls) {
        Map<String, Object> schema = new HashMap<>();
        schema.put("type", "object");

        Map<String, Object> properties = new HashMap<>();

        if (cls.isRecord()) {
            RecordComponent[] components = cls.getRecordComponents();
            for (RecordComponent rc : components) {
                properties.put(rc.getName(), schemaForType(rc.getGenericType()));
            }
        } else {
            for (java.lang.reflect.Field f : cls.getDeclaredFields()) {
                if (java.lang.reflect.Modifier.isStatic(f.getModifiers())) continue;
                properties.put(f.getName(), schemaForType(f.getGenericType()));
            }
        }

        schema.put("properties", properties);
        return schema;
    }
}

